platform_name: nccs_discover_sles15
is_it_me:
  - command: 'hostname'
    contains: discover
  - command: 'cat /etc/os-release | grep VERSION='
    contains: '15-'
crtm_coeffs_path: '/discover/nobackup/projects/gmao/advda/SwellStaticFiles/jedi/crtm_coefficients/'
crtm_coeffs_version: '2.4.1_skylab_4.0'
modules:
  default_modules: intel
  intel:
    init:
      - source /usr/share/lmod/lmod/init/bash
    load:
      - module purge
      - module use /discover/swdev/gmao_SIteam/modulefiles-SLES15
      - module use /discover/swdev/jcsda/spack-stack/scu17/modulefiles
      - module use /gpfsm/dswdev/jcsda/spack-stack/scu17/spack-stack-2.0.0/envs/ue-oneapi-2024.2.0/modules/Core
      - module load stack-intel-oneapi-compilers/2024.2.0
      - module load stack-intel-oneapi-mpi/2021.13
      - module load jedi-fv3-env
      - module load soca-env
      - module load gmao-swell-env/1.0.0
      - module unload gsibec crtm fms
      - module load fms/2024.02
      - module load ip/5.4.0
    configure: -DMPIEXEC_EXECUTABLE="/usr/local/intel/oneapi/2024/mpi/2021.13/bin/mpirun" -DMPIEXEC_NUMPROC_FLAG="-np"
  intel-geos:
    init:
      - source /usr/share/lmod/lmod/init/bash
    load:
      - module purge
      - module use /discover/swdev/gmao_SIteam/modulefiles-SLES15
      - module use /discover/swdev/jcsda/spack-stack/scu17/modulefiles
      - module use /gpfsm/dswdev/jcsda/spack-stack/scu17/spack-stack-2.0.0/envs/ue-oneapi-2024.2.0/modules/Core
      - module load stack-intel-oneapi-compilers/2024.2.0
      - module load stack-intel-oneapi-mpi/2021.13
      - module load jedi-fv3-env
      - module load soca-env
      - module load gmao-swell-env/1.0.0
      - module unload gsibec crtm fms
      - module load fms/2024.02
      - module load ip/5.4.0
      - module load esmf python py-pyyaml py-numpy pflogger fargparse zlib-ng cmake
    configure: -DMPIEXEC_EXECUTABLE="/usr/local/intel/oneapi/2024/mpi/2021.13/bin/mpirun" -DMPIEXEC_NUMPROC_FLAG="-np"
  intel-oneapi:
    init:
      - source /usr/share/lmod/lmod/init/bash
    load:
      - module purge
      - module use /discover/swdev/gmao_SIteam/modulefiles-SLES15
      - module use /discover/swdev/jcsda/spack-stack/scu17/modulefiles
      - module use /gpfsm/dswdev/jcsda/spack-stack/scu17/spack-stack-2.0.0/envs/ue-oneapi-2024.2.0/modules/Core
      - module load stack-intel-oneapi-compilers/2024.2.0
      - module load stack-intel-oneapi-mpi/2021.13
      - module load jedi-fv3-env
      - module load soca-env
      - module load gmao-swell-env/1.0.0
      - module unload gsibec crtm fms
      - module load fms/2024.02
      - module load ip/5.4.0
    configure: -DMPIEXEC_EXECUTABLE="/usr/local/intel/oneapi/2024/mpi/2021.13/bin/mpirun" -DMPIEXEC_NUMPROC_FLAG="-np"
  intel-oneapi-geos:
    init:
      - source /usr/share/lmod/lmod/init/bash
    load:
      - module purge
      - module use /discover/swdev/gmao_SIteam/modulefiles-SLES15
      - module use /discover/swdev/jcsda/spack-stack/scu17/modulefiles
      - module use /gpfsm/dswdev/jcsda/spack-stack/scu17/spack-stack-2.0.0/envs/ue-oneapi-2024.2.0/modules/Core
      - module load stack-intel-oneapi-compilers/2024.2.0
      - module load stack-intel-oneapi-mpi/2021.13
      - module load jedi-fv3-env
      - module load soca-env
      - module load gmao-swell-env/1.0.0
      - module unload gsibec crtm fms
      - module load fms/2024.02
      - module load ip/5.4.0
      - module load cmake esmf/8.8.0 gftl gftl-shared pflogger fargparse udunits
    configure: -DMPIEXEC_EXECUTABLE="/usr/local/intel/oneapi/2024/mpi/2021.13/bin/mpirun" -DMPIEXEC_NUMPROC_FLAG="-np"
  gnu:
    init:
      - source /usr/share/lmod/lmod/init/bash
    load:
      - module purge
      - module use /discover/swdev/gmao_SIteam/modulefiles-SLES15
      - module use /discover/swdev/jcsda/spack-stack/scu17/modulefiles
      - module use /gpfsm/dswdev/jcsda/spack-stack/scu17/spack-stack-2.0.0/envs/ue-gcc-13.4.0/install/modulefiles/Core
      - module load stack-gcc/13.4.0
      - module load jedi-fv3-env
      - module load soca-env
      - module load gmao-swell-env/1.0.0
      - module unload gsibec crtm fms
      - module load fms/2024.02
      - module load ip/5.4.0
    configure: -DMPIEXEC_EXECUTABLE="/usr/bin/srun" -DMPIEXEC_NUMPROC_FLAG="-n"
  gnu-geos:
    init:
      - source /usr/share/lmod/lmod/init/bash
    load:
      - module purge
      - module use /discover/swdev/gmao_SIteam/modulefiles-SLES15
      - module use /discover/swdev/jcsda/spack-stack/scu17/modulefiles
      - module use /gpfsm/dswdev/jcsda/spack-stack/scu17/spack-stack-2.0.0/envs/ue-gcc-13.4.0/install/modulefiles/Core
      - module load stack-gcc/13.4.0
      - module load jedi-fv3-env
      - module load soca-env
      - module load gmao-swell-env/1.0.0
      - module unload gsibec crtm fms
      - module load fms/2024.02
      - module load ip/5.4.0
      - module load esmf python py-pyyaml py-numpy pflogger fargparse zlib-ng cmake
    configure: -DMPIEXEC_EXECUTABLE="/usr/bin/srun" -DMPIEXEC_NUMPROC_FLAG="-n"
