platform_name: nccs_discover_sles15
is_it_me:
  - command: 'hostname'
    contains: discover
  - command: 'cat /etc/os-release | grep VERSION='
    contains: '15-'
crtm_coeffs_path: '/discover/nobackup/projects/gmao/advda/SwellStaticFiles/jedi/crtm_coefficients/'
crtm_coeffs_version: '2.4.0_skylab_3.0'
modules:
  default_modules: intel
  intel:
    init:
      - source /usr/share/lmod/lmod/init/bash
    load:
      - module purge
      - module use /discover/swdev/gmao_SIteam/modulefiles-SLES15
      - module use /discover/swdev/jcsda/spack-stack/scu17/modulefiles
      - module load ecflow/5.11.4
      - module use /gpfsm/dswdev/jcsda/spack-stack/scu17/spack-stack-20240228/envs/unified-env-intel-2021.10.0/install/modulefiles/Core
      - module load stack-intel/2021.10.0
      - module load stack-intel-oneapi-mpi/2021.10.0
      - module load stack-python/3.10.13
      - module load jedi-fv3-env
      - module load soca-env
      - module load gmao-swell-env/1.0.0
      - module unload gsibec crtm
    configure: -DMPIEXEC_EXECUTABLE="/usr/local/intel/oneapi/2021/mpi/2021.10.0/bin/mpirun" -DMPIEXEC_NUMPROC_FLAG="-np"
  gnu:
    init:
      - source /usr/share/lmod/lmod/init/bash
    load:
      - module purge
      - module use /discover/swdev/gmao_SIteam/modulefiles-SLES15
      - module use /discover/swdev/jcsda/spack-stack/scu17/modulefiles
      - module load ecflow/5.11.4
      - module use /gpfsm/dswdev/jcsda/spack-stack/scu17/spack-stack-20240228/envs/unified-env-gcc-12.3.0/install/modulefiles/Core
      - module load stack-gcc/12.3.0
      - module load stack-openmpi/4.1.6
      - module load stack-python/3.10.13
      - module load jedi-fv3-env
      - module load soca-env
      - module load gmao-swell-env/1.0.0
      - module unload gsibec crtm
    configure: -DMPIEXEC_EXECUTABLE="/usr/bin/srun" -DMPIEXEC_NUMPROC_FLAG="-n"
